export const menus = () => {
  return {
    component: [
      {
        name: '基础组件',
        enName: 'basic',
        link: '',
        children: [
          {
            name: 'Button 按钮',
            enName: 'Button',
            type: 'component',
            show: true,
            describe: '按钮用于触发一个操作，如提交表单。',
            author: 'kviewui@163.com',
            link: '/components/button',
          },
          {
            name: 'Cell 单元格',
            enName: 'Cell',
            type: 'component',
            show: true,
            describe: '列表项，可组成列表。',
            author: 'kviewui@163.com',
            link: '/components/cell',
          },
          {
            name: 'Image 图片',
            enName: 'Image',
            type: 'component',
            show: true,
            describe: '增强版的 img 标签，提供多种图片填充模式，支持图片加载中提示、加载失败提示。',
            author: 'kviewui@163.com',
            link: '/components/image',
          },
          {
            name: 'Icon 图标',
            enName: 'Icon',
            type: 'component',
            show: true,
            describe: '可支持多种 字体图标平台的图标集，可以通过 Icon 组件使用。',
            author: 'kviewui@163.com',
            link: '/components/icon',
          },
          {
            name: 'Tag 标签',
            enName: 'Tag',
            type: 'component',
            show: true,
            describe: '用于标记关键词和主要内容。',
            author: 'kviewui@163.com',
            link: '/components/tag',
          },
          {
            name: 'Badge 徽标',
            enName: 'Badge',
            type: 'component',
            show: true,
            describe: '展示图标或文字右上角的红色圆点、数字或者文字，表示有新内容或新消息待处理。',
            author: 'kviewui@163.com',
            link: '/components/badge',
          },
        ],
      },
      {
        name: '布局组件',
        enName: 'layout',
        link: '',
        children: [
          {
            name: 'Layout 布局',
            enName: 'layout',
            type: 'component',
            show: true,
            describe: 'Layout 提供了 kui-row 和 kui-col 两个辅助布局的组件，帮助您高效率的进行页面布局。',
            author: 'kviewui@163.com',
            link: '/components/layout',
          },
          {
            name: 'Grid 宫格',
            enName: 'grid',
            type: 'component',
            show: true,
            describe: '将页面区域分隔成等宽区块。',
            author: 'kviewui@163.com',
            link: '/components/grid',
          },
          {
            name: 'Divider 分割线',
            enName: 'divider',
            type: 'component',
            show: true,
            describe: '用于将内容分隔为多个区域。',
            author: 'kviewui@163.com',
            link: '/components/divider',
          },
          {
            name: 'Space 间隔',
            enName: 'space',
            type: 'component',
            show: true,
            describe: '在 kui-space 组件包裹下可以给行或者列增加内间距。',
            author: 'kviewui@163.com',
            link: '/components/space',
          },
          {
            name: 'Sticky 粘性布局',
            enName: 'sticky',
            type: 'component',
            show: true,
            describe: 'Sticky组件基于CSS中的 position: sticky 属性实现的效果，当组件在屏幕或者指定容器范围内时，按照正常的布局排列，当组件超出屏幕或者指定容器范围时，始终固定在屏幕或者指定容器顶部。',
            author: 'kviewui@163.com',
            link: '/components/sticky',
          },
        ],
      },
      {
        name: '展示组件',
        enName: 'show',
        link: '',
        children: [
          {
            name: 'Spin 加载动画',
            enName: 'spin',
            type: 'component',
            show: true,
            describe: 'Spin 组件提供了 15 种常见的CSS3加载场景动画，基本满足各种常见的等待加载场景需求。',
            author: 'kviewui@163.com',
            link: '/components/spin',
          },
          {
            name: 'Overlay 遮罩',
            enName: 'overlay',
            type: 'component',
            show: true,
            describe: '创建一个遮罩层，用来强调特定的元素，防止用户进行其他操作。',
            author: 'kviewui@163.com',
            link: '/components/overlay',
          },
          {
            name: 'Animation 动效',
            enName: 'animation',
            type: 'component',
            show: true,
            describe: '给元素添加常用的动画效果，Animation 基于 animista 总结而来，目前支持 10+ 种主轴动画形式。',
            author: 'kviewui@163.com',
            link: '/components/animation',
          },
          {
            name: 'Collapse 折叠面板',
            enName: 'collapse',
            type: 'component',
            show: true,
            describe: '将内容放置在多个折叠面板中，点击面板标题可展开或收缩内容。',
            author: 'kviewui@163.com',
            link: '/components/collapse',
          },
          {
            name: 'Skeleton 骨架屏',
            enName: 'skeleton',
            type: 'component',
            show: true,
            describe: '在页面上待加载区域填充灰色的占位图，用来展示界面加载过程的过渡效果。组件提供了标题，段落，头像，卡片等场景骨架，具体可参考下面代码演示部分。',
            author: 'kviewui@163.com',
            link: '/components/skeleton',
          },
          {
            name: 'Progress 进度条',
            enName: 'progress',
            type: 'component',
            show: true,
            describe: '用来展示当前操作的进度。',
            author: 'kviewui@163.com',
            link: '/components/progress',
          },
        ],
      },
      {
        name: '反馈组件',
        enName: 'feedback',
        link: '',
        children: [
          {
            name: 'Popup 弹出层',
            enName: 'popup',
            type: 'component',
            show: true,
            describe: '弹出层容器，用来展示弹窗，提示信息等内容，支持多个弹出层叠加展示。',
            author: 'kviewui@163.com',
            link: '/components/popup',
          },
          {
            name: 'Snackbar 消息条',
            enName: 'snackbar',
            type: 'component',
            show: true,
            describe: '在页面顶部或者底部展示消息提示。',
            author: 'kviewui@163.com',
            link: '/components/snackbar',
          },
          {
            name: 'ActionSheet 动作面板',
            enName: 'actionSheet',
            type: 'component',
            show: true,
            describe: '从底部弹出一个动作面板供用户选择选项。',
            author: 'kviewui@163.com',
            link: '/components/actionsheet',
          },
          {
            name: 'Dialog 对话框',
            enName: 'dialog',
            type: 'component',
            show: true,
            describe: '模态对话框，引导用户进行相关操作，常用于消息提示，消息确认，或在当前页面内完成特定的操作。',
            author: 'kviewui@163.com',
            link: '/components/dialog',
          },
          {
            name: 'Toast 吐司',
            enName: 'toast',
            type: 'component',
            show: true,
            describe: '用于轻提示内容场景。',
            author: 'kviewui@163.com',
            link: '/components/toast',
          },
        ],
      },
      {
        name: '表单组件',
        enName: 'form',
        link: '',
        children: [
          {
            name: 'Switch 开关',
            enName: 'switch',
            type: 'component',
            show: true,
            describe: '用来切换打开和关闭状态',
            author: 'kviewui@163.com',
            link: '/components/switch',
          },
          {
            name: 'Radio 单选按钮',
            enName: 'radio',
            type: 'component',
            show: true,
            describe: '在一组备选项中进行单选。',
            author: 'kviewui@163.com',
            link: '/components/radio',
          },
          {
            name: 'Checkbox 复选按钮',
            enName: 'checkbox',
            type: 'component',
            show: true,
            describe: '在一组备选项中进行多选。',
            author: 'kviewui@163.com',
            link: '/components/checkbox',
          },
          {
            name: 'Input 输入框',
            enName: 'input',
            type: 'component',
            show: true,
            describe: '用户可以在文本框内输入内容。',
            author: 'kviewui@163.com',
            link: '/components/input',
          },
          {
            name: 'Stepper 步进器',
            enName: 'stepper',
            type: 'component',
            show: true,
            describe: '由增加按钮、输入框和减少按钮组成，用户可以在输入框内直接输入数字，也可以通过增加按钮和减少按钮控制输入框内的数字增减，常用在比如购物车、直接购买物品等场景增加减少物品数量。',
            author: 'kviewui@163.com',
            link: '/components/stepper',
          },
          {
            name: 'Numberkeyboard 数字键盘',
            enName: 'numberkeyboard',
            type: 'component',
            show: true,
            describe: '虚拟数字键盘，用于输入密码或验证码的场景，可以配合 <a href="short-password">ShortPassword 短密码组件</a> 或自定义输入框组件使用。',
            link: '/components/numberkeyboard',
          },
          {
            name: 'Picker 选择器',
            enName: 'picker',
            type: 'component',
            show: true,
            describe: '底部弹出多项集合供用户滚动选择其中一项。',
            link: '/components/picker',
          },
          {
            name: 'Rate 评分',
            enName: 'rate',
            type: 'component',
            show: true,
            describe: '用于快速的评级操作，或对评级进行展示。',
            link: '/components/rate',
          },
          {
            name: 'Slider 滑块',
            enName: 'slider',
            type: 'component',
            show: true,
            describe: '滑动输入条，用于在给定范围内选择一个值。',
            link: '/components/slider',
          },
          {
            name: 'SearchBar 搜索栏',
            enName: 'searchbar',
            type: 'component',
            show: true,
            describe: '用于搜索场景的输入框组件。',
            link: '/components/searchbar',
          },
          {
            name: 'ShortPassword 短密码',
            enName: 'shortpassword',
            type: 'component',
            show: true,
            describe: '短密码输入框，常用于密码输入和短信验证码输入，可搭配 `Numberkeyboard 数字键盘` 组件一起使用',
            link: '/components/shortpassword',
          },
          {
            name: 'Uploader 上传',
            enName: 'uploader',
            type: 'component',
            show: true,
            describe: '用于将本地的图片或文件上传到服务器场景。',
            link: '/components/uploader',
          },
        ],
      },
    ],
    guide: [
      {
        name: '介绍',
        enName: 'intro',
        type: 'guide',
        show: true,
        describe: '',
        link: '/guide/intro',
        children: [],
      },
      {
        name: '快速上手',
        enName: 'start',
        type: 'guide',
        show: true,
        describe: '',
        link: '/guide/start',
        children: [],
      },
      {
        name: '颜色',
        enName: 'palette',
        type: 'guide',
        show: true,
        describe: '',
        link: '/guide/palette',
        children: [],
      },
      {
        name: '设计变量',
        enName: 'token',
        type: 'guide',
        show: true,
        describe: '',
        link: '/guide/token',
        children: [],
      },
      {
        name: 'CSS全局样式库',
        enName: 'css',
        link: '',
        children: [
          {
            name: '介绍',
            enName: 'intro',
            type: 'guide',
            show: true,
            describe: '由于业内CSS原子化的盛行，组件库参考tailwindcss的设计思路，并且结合UNIAPP NVUE的样式支持给大家提供了一套原子化的CSS样式库，助力各位开发者用户高效开发业务。',
            author: 'kviewui@163.com',
            link: '/guide/css/intro',
          },
          {
            name: 'Box Sizing',
            enName: 'boxSizing',
            type: 'guide',
            show: true,
            describe: '控制浏览器如何计算元素的总大小的功能类。',
            author: 'kviewui@163.com',
            link: '/guide/css/box-sizing',
          },
          {
            name: 'Display',
            enName: 'display',
            type: 'guide',
            show: true,
            describe: '控制元素显示类型的功能类',
            author: 'kviewui@163.com',
            link: '/guide/css/display',
          },
          {
            name: '溢出',
            enName: 'overflow',
            type: 'guide',
            show: true,
            describe: '',
            author: 'kviewui@163.com',
            link: '/guide/css/overflow',
          },
          {
            name: '定位',
            enName: 'position',
            type: 'guide',
            show: true,
            describe: '用于控制元素在DOM中的位置的功能类。',
            author: 'kviewui@163.com',
            link: '/guide/css/position',
          },
          {
            name: '定位位置',
            enName: 'top-right-bottom-left',
            type: 'guide',
            show: true,
            describe: '用于控制定位元素的位置的功能类。',
            author: 'kviewui@163.com',
            link: '/guide/css/top-right-bottom-left',
          },
          {
            name: '层级',
            enName: 'z-index',
            type: 'guide',
            show: true,
            describe: '用于控制元素的堆栈顺序的功能类。',
            author: 'kviewui@163.com',
            link: '/guide/css/z-index',
          },
          {
            name: 'Flex方向',
            enName: 'flex-direction',
            type: 'guide',
            show: true,
            describe: '控制 Flex 子项的方向的功能类',
            author: 'kviewui@163.com',
            link: '/guide/css/flex-direction',
          },
          {
            name: 'Flex Wrap',
            enName: 'flex-wrap',
            type: 'guide',
            show: true,
            describe: '控制 Flex 子项是否换行的功能类',
            author: 'kviewui@163.com',
            link: '/guide/css/flex-wrap',
          },
          {
            name: 'Flex',
            enName: 'flex',
            type: 'guide',
            show: true,
            describe: '用于控制 flex 项目放大和缩小的功能类。',
            author: 'kviewui@163.com',
            link: '/guide/css/flex',
          },
          {
            name: 'Flex Grow',
            enName: 'flex-grow',
            type: 'guide',
            show: true,
            describe: '控制 flex 项目放大的功能类',
            author: 'kviewui@163.com',
            link: '/guide/css/flex-grow',
          },
          {
            name: 'Flex Shrink',
            enName: 'flex-shrink',
            type: 'guide',
            show: true,
            describe: '控制 flex 项目缩小的功能类',
            author: 'kviewui@163.com',
            link: '/guide/css/flex-shrink',
          },
          {
            name: 'Grid Template Columns',
            enName: 'grid-template-columns',
            type: 'guide',
            show: true,
            describe: '用于在网格布局中指定列的功能类。',
            author: 'kviewui@163.com',
            link: '/guide/css/grid-template-columns',
          },
          {
            name: 'Grid Column',
            enName: 'grid-column',
            type: 'guide',
            show: true,
            describe: '用于控制在网格列中元素的大小和放置方式的功能类。',
            author: 'kviewui@163.com',
            link: '/guide/css/grid-column',
          },
        ],
      },
    ],
  }
}
