import type MdConfig from './docs.type'

export const mdConfig = () => {
  const baseLink = 'https://gitee.com/bad_-code/kviewui/tree/master/components'

  return <MdConfig>{
    button: {
      // 组件源码仓库地址
      linkCode: `${baseLink}/kui-button`,
      // 演示代码组件映射
      showPath: {
        'block': 'button/BlockButton',
        'custom-color': 'button/CustomColorButton',
        'disabled': 'button/DisabledButton',
        'icon': 'button/IconButton',
        'loading': 'button/LoadingButton',
        'shadow': 'button/ShadowButton',
        'shape': 'button/ShapeButton',
        'size': 'button/SizeButton',
        'text': 'button/TextButton',
        'theme': 'button/ThemeButton',
      },
    },
    cell: {
      linkCode: `${baseLink}/kui-cell`,
      showPath: {
        'base': 'cell/BaseCell',
        'slot': 'cell/SlotCell',
        'link-group-base': 'cell/LinkGroupBaseCell',
        'link-group-space': 'cell/LinkGroupSpaceCell',
        'left-icon': 'cell/LeftIconCell',
        'icon': 'cell/IconCell',
        'center': 'cell/CenterCell',
      },
    },
    image: {
      linkCode: `${baseLink}/kui-image`,
      showPath: {
        base: 'image/BaseImage',
        mode: 'image/ModeImage',
        radius: 'image/RadiusImage',
        error: 'image/ErrorImage',
        click: 'image/ClickImage',
        preview: 'image/PreviewImage',
        lazyload: 'image/LazyloadImage',
      },
    },
    icon: {
      linkCode: `${baseLink}/kui-icons`,
      showPath: {
        'base': 'icon/BaseIcon',
        'color': 'icon/ColorIcon',
        'size': 'icon/SizeIcon',
        'weight': 'icon/WeightIcon',
        'animation': 'icon/AnimationIcon',
        'class-animation': 'icon/ClassAnimationIcon',
        'custom': 'icon/CustomIcon',
        'iconfont': 'icon/IconfontIcon',
        'iconfont3': 'icon/Iconfont3Icon',
        'iconfont-css': 'icon/IconfontCssIcon',
        'iconfont-html': 'icon/IconfontHtmlIcon',
      },
    },
    tag: {
      linkCode: `${baseLink}/kui-tag`,
      showPath: {
        'type': 'tag/TypeTag',
        'plain': 'tag/PlainTag',
        'shape': 'tag/ShapeTag',
        'size': 'tag/SizeTag',
        'block': 'tag/BlockTag',
        'half-round': 'tag/HalfRoundTag',
        'closable': 'tag/ClosableTag',
        'loading': 'tag/LoadingTag',
        'checkable': 'tag/CheckableTag',
        'custom-color': 'tag/CustomColorTag',
        'slot': 'tag/SlotTag',
      },
    },
    badge: {
      linkCode: `${baseLink}/kui-badge`,
      showPath: {
        type: 'badge/TypeBadge',
        dot: 'badge/DotBadge',
        value: 'badge/ValueBadge',
        gradient: 'badge/GradientBadge',
        max: 'badge/MaxBadge',
        position: 'badge/PositionBadge',
        show: 'badge/ShowBadge',
        color: 'badge/ColorBadge',
        icon: 'badge/IconBadge',
      },
    },
    layout: {
      linkCode: `${baseLink}`,
      showPath: {
        base: 'layout/BaseLayout',
        gutter: 'layout/GutterLayout',
        flex: 'layout/FlexLayout',
      },
    },
    grid: {
      linkCode: `${baseLink}/kui-grid`,
      showPath: {
        'base': 'grid/BaseGrid',
        'columns': 'grid/ColumnsGrid',
        'gutter': 'grid/GutterGrid',
        'reverse': 'grid/ReverseGrid',
        'direction': 'grid/DirectionGrid',
        'icon-color-size': 'grid/IconColorSizeGrid',
        'slot': 'grid/SlotGrid',
      },
    },
    divider: {
      linkCode: `${baseLink}/kui-divider`,
      showPath: {
        'base': 'divider/BaseDivider',
        'dashed': 'divider/DashedDivider',
        'inset': 'divider/InsetDivider',
        'direction': 'divider/DirectionDivider',
        'slot': 'divider/SlotDivider',
        'text-direction': 'divider/TextDirectionDivider',
        'min-px': 'divider/MinPxDivider',
        'color-theme': 'divider/ColorThemeDivider',
      },
    },
    space: {
      linkCode: `${baseLink}/kui-space`,
      showPath: {
        'base': 'space/BaseSpace',
        'direction': 'space/DirectionSpace',
        'gap': 'space/GapSpace',
        'justify-end': 'space/JustifyEndSpace',
        'justify-space-around': 'space/JustifySpaceAroundSpace',
        'justify-center': 'space/JustifyCenterSpace',
        'justify-space-between': 'space/JustifySpaceBetweenSpace',
      },
    },
    sticky: {
      linkCode: `${baseLink}/kui-sticky`,
      showPath: {
        'base': 'sticky/BaseSticky',
        'top': 'sticky/TopSticky',
        'container': 'sticky/ContainerSticky',
        'bottom': 'sticky/BottomSticky',
        'container-ts': 'sticky/ContainerTsSticky',
      },
    },
    spin: {
      linkCode: `${baseLink}/kui-spin`,
      showPath: {
        'base': 'spin/BaseSpin',
        'theme': 'spin/ThemeSpin',
        'background-color': 'spin/BackgroundColorSpin',
        'size': 'spin/SizeSpin',
      },
    },
    overlay: {
      linkCode: `${baseLink}/kui-overlay`,
      showPath: {
        'base': 'overlay/BaseOverlay',
        'overlay-ness': 'overlay/OverlayNessOverlay',
        'content': 'overlay/ContentOverlay',
        'vnode': 'overlay/VnodeOverlay',
        'slot-default': 'overlay/SlotDefaultOverlay',
        'blur': 'overlay/BlurOverlay',
      },
    },
    animation: {
      linkCode: `${baseLink}/kui-animation`,
      showPath: {
        'base': 'animation/BaseAnimation',
        'duration': 'animation/DurationAnimation',
        'duration-unit': 'animation/DurationUnitAnimation',
        'timing-function': 'animation/TimingFunctionAnimation',
        'delay': 'animation/DelayAnimation',
        'delay-unit': 'animation/DelayUnitAnimation',
        'interation-count': 'animation/InterationCountAnimation',
        'infinite': 'animation/InfiniteAnimation',
        'direction': 'animation/DirectionAnimation',
        'fill-mode': 'animation/FillModeAnimation',
        'runing': 'animation/RuningAnimation',
        'demo': 'animation/DemoAnimation',
        'demo-ts': 'animation/DemoTsAnimation',
      },
    },
    collapse: {
      linkCode: `${baseLink}/kui-collapse`,
      showPath: {
        'base': 'collapse/BaseCollapse',
        'disabled': 'collapse/DisabledCollapse',
        'accordion': 'collapse/AccordionCollapse',
        'taped-state': 'collapse/TapedStateCollapse',
        'animation': 'collapse/AnimationCollapse',
        'colors': 'collapse/ColorsCollapse',
        'slots': 'collapse/SlotsCollapse',
      },
    },
    skeleton: {
      linkCode: `${baseLink}/kui-skeleton`,
      showPath: {
        'base': 'skeleton/BaseSkeleton',
        'title': 'skeleton/TitleSkeleton',
        'rows': 'skeleton/RowsSkeleton',
        'rows-round': 'skeleton/RowsRoundSkeleton',
        'avatar': 'skeleton/AvatarSkeleton',
        'card': 'skeleton/CardSkeleton',
        'layout': 'skeleton/LayoutSkeleton',
        'animate': 'skeleton/AnimateSkeleton',
        'animate-type': 'skeleton/AnimateTypeSkeleton',
      },
    },
    progress: {
      linkCode: `${baseLink}/kui-progress`,
      showPath: {
        'base': 'progress/BaseProgress',
        'width-color': 'progress/WidthColorProgress',
        'label': 'progress/LabelProgress',
        'label-inside': 'progress/LabelInsideProgress',
        'slot-label-inside': 'progress/SlotLabelInsideProgress',
        'active': 'progress/ActiveProgress',
        'icon-name': 'progress/IconNameProgress',
        'shape': 'progress/ShapeProgress',
        'demo': 'progress/DemoProgress',
      },
    },
    popup: {
      linkCode: `${baseLink}/kui-popup`,
      showPath: {
        'base': 'popup/BasePopup',
        'position': 'popup/PositionPopup',
        'radius-size': 'popup/RadiusSizePopup',
        'icon': 'popup/IconPopup',
        'close': 'popup/ClosePopup',
        'callback': 'popup/CallbackPopup',
      },
    },
    snackbar: {
      linkCode: `${baseLink}/kui-snackbar`,
      showPath: {
        'base': 'snackbar/BaseSnackbar',
        'type': 'snackbar/TypeSnackbar',
        'plain': 'snackbar/PlainSnackbar',
        'full': 'snackbar/FullSnackbar',
        'custom-style': 'snackbar/CustomStyleSnackbar',
        'content-center': 'snackbar/ContentCenterSnackbar',
        'position': 'snackbar/PositionSnackbar',
        'duration': 'snackbar/DurationSnackbar',
      },
    },
    actionsheet: {
      linkCode: `${baseLink}/kui-actionsheet`,
      showPath: {
        'base': 'actionsheet/BaseActionsheet',
        'cancel': 'actionsheet/CancelActionsheet',
        'title-desc': 'actionsheet/TitleDescActionsheet',
        'status': 'actionsheet/StatusActionsheet',
      },
    },
    dialog: {
      linkCode: `${baseLink}/kui-dialog`,
      showPath: {
        normal: 'dialog/NormalDialog',
        content: 'dialog/ContentDialog',
        type: 'dialog/TypeDialog',
        footer: 'dialog/FooterDialog',
      },
    },
    toast: {
      linkCode: `${baseLink}/kui-toast`,
      showPath: {
        base: 'toast/BaseToast',
        type: 'toast/TypeToast',
        overlay: 'toast/OverlayToast',
      },
    },
    switch: {
      linkCode: `${baseLink}/kui-switch`,
      showPath: {
        base: 'switch/BaseSwitch',
        disabled: 'switch/DisabledSwitch',
        loading: 'switch/LoadingSwitch',
        change: 'switch/ChangeSwitch',
        async: 'switch/AsyncSwitch',
        colors: 'switch/ColorsSwitch',
        text: 'switch/TextSwitch',
      },
    },
    radio: {
      linkCode: `${baseLink}/kui-radio`,
      showPath: {
        'base': 'radio/BaseRadio',
        'row': 'radio/RowRadio',
        'icon': 'radio/IconRadio',
        'icon-size': 'radio/IconSizeRadio',
        'icon-color': 'radio/IconColorRadio',
        'change': 'radio/ChangeRadio',
      },
    },
  }
}
