// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert.vue')['default']
    Asider: typeof import('./components/Asider.vue')['default']
    ChangeMode: typeof import('./components/ChangeMode.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    CssPrefix: typeof import('./components/docs/guide/CssPrefix.md')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Home: typeof import('./components/Home.md')['default']
    Palette: typeof import('./components/Palette.vue')['default']
    Palettes: typeof import('./components/Palettes.vue')['default']
    PropsModeProp: typeof import('./components/docs/props/PropsModeProp.md')['default']
    PropsRulesProp: typeof import('./components/docs/props/PropsRulesProp.md')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowCode: typeof import('./components/ShowCode.vue')['default']
    Simulator: typeof import('./components/Simulator.vue')['default']
    Tag: typeof import('./components/docs/Tag.vue')['default']
    TipsDemoWarning: typeof import('./components/docs/tips/TipsDemoWarning.md')['default']
    TipsIntroduce: typeof import('./components/docs/tips/TipsIntroduce.md')['default']
    TokenColors: typeof import('./components/docs/guide/TokenColors.vue')['default']
  }
}
