// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert.vue')['default']
    Asider: typeof import('./components/Asider.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Home: typeof import('./components/Home.md')['default']
    PropsModeProp: typeof import('./components/docs/props/PropsModeProp.md')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowCode: typeof import('./components/ShowCode.vue')['default']
    Simulator: typeof import('./components/Simulator.vue')['default']
    TipsDemoWarning: typeof import('./components/docs/tips/TipsDemoWarning.md')['default']
    TipsIntroduce: typeof import('./components/docs/tips/TipsIntroduce.md')['default']
  }
}
